custom:
   defaultRegion: us-east-2
   region: ${opt:region, self:custom.defaultRegion}
   stage: ${opt:stage, env:USER}
   standardRequest:
      template:
         application/json: ${file(./templates.yml):request}
   standardResponseHeaders:
      'Access-Control-Allow-Origin': "'*'"
      'Content-Type': 'integration.response.body.headers.Content-Type'
      'Expires': 'integration.response.body.headers.Expires'
      'Cache-Control': 'integration.response.body.headers.Cache-Control'
      'Pragma': "'no-cache'"
   standardResponseTemplate: "$input.path('$.body')"
   errorResponseHeaders:
      'Access-Control-Allow-Origin': "'*'"
      'Expires': "'Thu, 19 Nov 1981 08:52:00 GMT'"
      'Cache-Control': "'no-cache, max-age=0, must-revalidate'"
      'Pragma': "'no-cache'"
   errorResponseTemplate: "$input.path('$.errorMessage')"
   # Here we are defining what would be under "responses" in your HTTP event
   # if you were not using the custom variables.
   standardResponses:
      200:
         headers: ${self:custom.standardResponseHeaders}
         templates:
            'application/json;charset=UTF-8': ${self:custom.standardResponseTemplate}
      404:
         headers: ${self:custom.errorResponseHeaders}
         templates:
            'application/json;charset=UTF-8': ${self:custom.errorResponseTemplate}
         properties:
            SelectionPattern: '.*\"status\":404.*'
      500:
         headers: ${self:custom.errorResponseHeaders}
         templates:
            'application/json;charset=UTF-8': ${self:custom.errorResponseTemplate}
         properties:
            SelectionPattern: '.*\"status\":500.*'
   redirectResponses:
      # Since we want to return 302 upon a successful completion, we remove the
      # built-in default of 200
      200: false
      302:
         headers:
            Location: "integration.response.body.headers.Location"
         templates:
            'application/json;charset=UTF-8': "$input.path('$.body')"
            'text/html;charset=UTF-8': "$input.path('$.body')"
      404:
         headers: ${self:custom.errorResponseHeaders}
         templates:
            'application/json;charset=UTF-8': "$input.path('$.body')"
            'text/html;charset=UTF-8': "$input.path('$.body')"
         properties:
            SelectionPattern: '.*\"status\":404.*'
      500:
         headers: ${self:custom.errorResponseHeaders}
         templates:
            'application/json;charset=UTF-8': "$input.path('$.body')"
            'text/html;charset=UTF-8': "$input.path('$.body')"
         properties:
            SelectionPattern: '.*\"status\":500.*'
